baseURL = "https://j-levy.github.io/"
languageCode = "en-us"
title = "Jonathan LEVY"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true
staticDir = [ "themes/hugo-profile/static/", "static/"]
[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

#[[Menus.main]]
#identifier = "blog"
#name = "Blog"
#title = "Blog posts"
#url = "/blogs"


#[[Menus.main]]
#identifier = "gallery"
#name = "Gallery"
#title = "Blog posts"
#url = "/gallery"
#weight = 2

[params]
title = "Jonathan LEVY"
description = "My presentation"
favicon = "/favicon-96x96.png"
useBootstrapCDN = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Jonathan LEVY"
  disableSearch = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = true
    disableContact = true

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Jonathan LEVY."
  subtitle = """I develop software. Maybe for you?"""
  content = "Whether it's working on desktop programs, high-performance computing software or just a website, when I'd like something to exist, I may end up doing it myself. " # Mainly versed in C++, CUDA and Python with a touch of Qt5.
  image = "/images/hero-hinotou.jpg"  # could be an SVG like "/images/hero.svg"

    [params.hero.button]
    enable = true
    name = "Resume"
    url = "/assets/resume_jonathan_levy.pdf"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/j-levy"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github-alt"
url = "https://github.com/yattoz"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-mastodon"
url = "https://piaille.fr/@lejo"

# [[params.hero.socialLinks.customIcons]]
# icon = "/fav.png"
# url = "https://example.com"

  [params.about]
  enable = true
  title = "About Me"
  image = "/images/photo.jpg"
  content = """
I am a French software developer, I like both low-level programming involving memory management or thread concurrency, and implementing graphical interfaces. My background is a mix of computer engineering, computer science and mechatronics, with a hint of science teaching. 

With a knack for multiculturalism and travel, I had the opportunity to study in France, the Netherlands and Japan, this last being where I currently live. I am finishing a 18-month period as Research Student at Osaka University where I studied possibilities of GPU acceleration for 3rd-generation DNA sequences alignment.

I am currently open for hire (and ready to move too!)

"""
    [params.about.skills]
    enable = true
    title = "Here are a few technologies I recently worked with:"
    items = [ "C++", "CUDA", "Qt5 & GUI", "HTML/CSS/JS", "Python", "Git" ]

  [params.experience]
  enable = true


    [[params.experience.items]]
    job = "Software Engineer"
    company = "Inria"
    companyUrl = "https://www.inria.fr"
    date = "Dec 2019 - Feb 2021"
    period =  "(1+ year)"
    content = "In the engineering team of the public research laboratory Inria, I contributed to desktop applications for research, like *GNOMON* (plant growth simulation) and *sw2d* (chemical dispersion in shallow waters). This involved scientific simulation with C++ and Python, 3D visualization with VTK and GUI with Qt5."

      [params.experience.items.featuredLink]
      enable = true
      name = "See activity on Inria's GitLab"
      url = "https://gitlab.inria.fr/users/jolevy/activity"

      [[params.experience.items]]
    job = "Software Engineer"
    company = "CIRAD"
    companyUrl = "https://www.cirad.fr"
    date = "Jun 2021 - Aug 2021"
    period = "(3 months)"
    content = "During my short period at CIRAD I helped defining the requirements for a 3D mesh catalogue for the Lindenmayer Systems software *lpy*. This software is used in research and academia to describing plant cells growth."

      [params.experience.items.featuredLink]
      enable = true
      name = "See on GitHub"
      url = "https://github.com/fredboudon/lpy/"



  [params.education]
  enable = true
  index = false

    [[params.education.items]]
    title = "Research Student - High-Performance Computing"
    date = "Sep 2021 - Mar 2023"
    GPA = "Non-graded"
    content = """
- Research on long-reads DNA alignment with GPUs
- Japanese language practice
- Considered Ph.D position but finally not interested
  """

      [params.education.items.school]
      name = "Osaka University (Japan)"
      url = "https://www.osaka-u.ac.jp/en"

    [[params.education.items]]
    title = "Master of Science - Embedded Systems"
    date = "2017 - 2019"
    GPA = "7.6 out of 10"
    content = """
Academia:
- Courses on computer architecture, software engineering, real-time embedded programming
- Electives on crowd-sourced computing, software architecture, high-performance computing
- Master Thesis on acceleration of DNA seed extension for the BWA-MEM DNA aligner using GPUs

Extracurricular Activities
  - Member of Delft E-Sports Association
  - Podcast production"""

      [params.education.items.school]
      name = "Delft University of Technology (Netherlands)"
      url = "https://www.tudelft.nl/en/"

      [params.education.items.featuredLink]
      enable = true
      name = "My master thesis"
      url = "https://repository.tudelft.nl/islandora/object/uuid%3Abd22471f-058a-4071-95bb-5126e263124b"

    [[params.education.items]]
    title = "Master of Science Teaching - Mechatronics"
    date = "2014 - 2017"
    GPA = "7.5 out of 10"
    content = """
- Double-BSc obtained with University of Rennes 1
  * Mechanical Engineering: structure engineering, beam theory, thermodynamics
  * Electrical Engineering: power electronics, networking, antennas science
  * Multiphysics simulation and 3D modeling
- Master degree for teaching from ENS Rennes
- Passed *Agrégation*, the certification for teachers in France
"""

      [params.education.items.school]
      name = "Ecole Normale Supérieure de Rennes (France)"
      url = "https://international.ens-rennes.fr/"

      [params.education.items.featuredLink]
      enable = true
      name = "check this out"
      url = "https://example.com"


  [params.projects]
  enable = true
  title = "Hobby projects"

    [[params.projects.items]]
    title = "Website: Calvinball Consortium"
    content = "Website and code for podcasts presentation for the Calvinball Consortium Podcast Network, along with various services (file hosting, voice chat server, user management with Cockpit)"

    image = "/images/projects/calvinball1.jpg"
    badges = [ "Hugo", "Ruby", "Javascript" ]

      [params.projects.items.featured]
      name = "See website"
      link = "https://www.calvinballconsortium.fr"

      # [[params.projects.items.links]]
      # icon = "fa fa-envelope"
      # url = "mailto:?subject=Calvinball%20Consortium%20Website"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/yattoz/calvinball-website"


    [[params.projects.items]]
    title = "Android app: Tsumugi Webradio"
    content = "An Android app to listen to the webradio Tsumugi, with convenient features: sleep, alarm, last played, news from the blog."
    image = "/images/projects/tsumugi.jpg"
    badges = [ "Android", "Kotlin" ]

      [params.projects.items.featured]
      name = "Google Play"
      link = "https://play.google.com/store/apps/details?id=fr.forum_thalie.tsumugi"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/yattoz/webradio-app"

    [[params.projects.items]]
    title = "Podcast Recommandé"
    content = "A podcast to discover music following YouTube recommendations (in French). 65 episodes in Dec. 2022 and counting! (every 2 weeks)"
    image = "/images/projects/recommande1.jpg"
    badges = [ "Music", "DAW", "Podcast" ]

      [params.projects.items.featured]
      name = "Latest episodes"
      link = "https://www.calvinballconsortium.fr/podcasts/recommande"

      [[params.projects.items.links]]
      icon = "fab fa-spotify"
      url = "https://open.spotify.com/show/4EtqYwTwE3Z138ST2C3cEz"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/recommande0"


  [params.achievements]
  enable = false

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."

    [[params.achievements.items]]
    title = "Hugo Profile"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"


  [params.contact]
  enable = false
  content = "Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  email = ""
  btnName = "Mail me"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = false
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/j-levy"
linkedin = "https://www.linkedin.com/in/jonathan-levy-867857254/?locale=en_US"
# twitter = "https://twitter.com"
# instagram = "https://instagram.com"
# facebook = "https://facebook.com"
mastodon = "https://piaille.fr/@lejo"
  [params.listPages]
  disableFeaturedImage = false
