baseURL = "https://j-levy.github.io/"
languageCode = "en-us"
title = "Jonathan LEVY"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true
staticDir = [ "static/", "themes/hugo-profile/static/"]
[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

[[Menus.main]]
identifier = "gallery"
name = "Gallery"
title = "Blog posts"
url = "/gallery"
weight = 2

[params]
title = "Jonathan LEVY"
description = "My presentation"
favicon = "/fav.png"
useBootstrapCDN = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Jonathan LEVY"
  disableSearch = false

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Jonathan LEVY."
  subtitle = "I develop software. Maybe for you?"
  content = "Mainly versed in C++, CUDA and Python with a touch of Qt5. When I'd like something to exist, I may end up making it myself. In the end, we are always programming for humans."
  image = "/images/hero.svg"

    [params.hero.button]
    enable = true
    name = "Resume"
    url = "/assets/resume_jonathan_levy.pdf"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/j-levy"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github-alt"
url = "https://github.com/yattoz"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-twitter"
url = "https://twitter.com/yattoz"

# [[params.hero.socialLinks.customIcons]]
# icon = "/fav.png"
# url = "https://example.com"

  [params.about]
  enable = true
  title = "About Me"
  image = "/images/me.png"
  content = """
I am a French software developer with a main focus on relatively low-level programming. My background is a mix of computer engineering, computer science and mechatronics, with a hint of science teaching. My last research project revolved around possibilities of 3rd generation DNA sequences alignment using GPUs as Osaka University (Japan).

With a knack for multiculturalism and travel, I had the opportunity to study in France, the Netherlands and Japan, this last being where I currently live. Be it for programming or for speaking, I don't hesitate to try another language.

I am currently open for hire.

"""
    [params.about.skills]
    enable = true
    title = "Here are a few technologies I'm quite at ease working with:"
    items = [ "C++", "CUDA", "Qt5 & GUI", "HTML/CSS/JS", "Python", "Git" ]

  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "Software Engineer"
    company = "Inria"
    companyUrl = "https://www.inria.fr"
    date = "Dec 2019 - Feb 2021"
    content = "In the engineering team of the public research laboratory Inria, I contributed to desktop applications for scientific research, like GNOMON (plant growth simulation) or sw2d (chemical dispersion in shallow waters). This involved scientific simulation with C++ and Python, 3D visualization with VTK and GUI with Qt5."

      [params.experience.items.featuredLink]
      enable = true
      name = "My activity on Inria GitLab"
      url = "https://gitlab.inria.fr/users/jolevy/activity"


  [params.education]
  enable = true
  index = false

    [[params.education.items]]
    title = "Research Student - High-Performance Computing"
    date = "Sep 2021 - Mar 2023"
    GPA = "Non-graded"
    content = """
- Researched on long-reads DNA alignment with GPUs
- Learned Japanese
- Considered Ph.D position but didn't like it
  """

      [params.education.items.school]
      name = "Osaka University (Japan)"
      url = "https://www.osaka-u.ac.jp/en"

    [[params.education.items]]
    title = "Master of Science - Embedded Systems"
    date = "2017 - 2019"
    GPA = "7.6 out of 10"
    content = """
Academia:
- Courses on computer architecture, software engineering & architecture
- Master Thesis on acceleration of DNA seed extension for the BWA-MEM DNA aligner using GPUs

Extracurricular Activities
  - Member of Delft E-Sports Association
  - Podcast production"""

      [params.education.items.school]
      name = "Delft University of Technology (Netherlands)"
      url = "https://www.tudelft.nl/en/"

      [params.education.items.featuredLink]
      enable = true
      name = "My master thesis"
      url = "https://repository.tudelft.nl/islandora/object/uuid%3Abd22471f-058a-4071-95bb-5126e263124b"

    [[params.education.items]]
    title = "Master of Science Teaching - Mechatronics"
    date = "2014 - 2017"
    GPA = "7.5 out of 10"
    content = """
- Double-BSc obtained with University of Rennes 1
  * Mechanical Engineering: structure engineering, beam theory, thermodynamics
  * Electrical Engineering: power electronics, networking, antennas science
  * Multiphysics simulation and 3D modeling
- Master degree for teaching from ENS Rennes
- Passed *Agrégation*, the certification for teachers in France
"""

      [params.education.items.school]
      name = "Ecole Normale Supérieure de Rennes (France)"
      url = "https://international.ens-rennes.fr/"

      [params.education.items.featuredLink]
      enable = true
      name = "check this out"
      url = "https://example.com"


  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Hugo Profile"
    content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
    image = "/images/projects/profile.png"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://hugo-profile.netlify.app"

      [[params.projects.items.links]]
      icon = "fa fa-envelope"
      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/hugo-profile"

      [[params.projects.items.links]]
      icon = "fab fa-twitter"
      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "Image Converter"
    content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
    image = "/images/projects/converter.jpg"
    badges = [ "Django", "Bootstrap" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://django-converter.herokuapp.com"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/converter"

    [[params.projects.items]]
    title = "Hugo Profile V2"
    content = "A clean and simple Hugo template for personal portfolio and blog."
    image = "/images/projects/profile2.jpg"
    badges = [ "Hugo", "Bootstrap", "Javascript" ]

      [params.projects.items.featured]
      name = "Demo V2"
      link = "https://hugo-profile-2.netlify.app"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.achievements]
  enable = true

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."

    [[params.achievements.items]]
    title = "Hugo Profile"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"


  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  email = "gurusabarisha@gmail.com"
  btnName = "Mail me"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com"
linkedin = "https://linkedin.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"
facebook = "https://facebook.com"

  [params.listPages]
  disableFeaturedImage = false
